### ISSUE TITLE
Query - register and create account

### ISSUE THREAD

**Issue by OGester** [Jerkinator/secondRoll#1]
Som användare vill jag kunna registrera en användare och skapa ett konto så man kan se och lägga till annonser.

**Comment by Vurpas** [comment]
secondroll> db.users.insertOne({created_at: Date(), updated_at: Date(), username: "Dansken", email: "teisloyche@hotmail.com", password: "speltorsk93", phoneNumber: "0768394211", adress_street: "Nordhemsgatan 72A", adress_zip: "41309", adress_city: "Göteborg"});
