### ISSUE TITLE
Query - create add

### ISSUE THREAD

**Issue by OGester** [Jerkinator/secondRoll#2]
Som användare vill jag kunna lägga upp ett spel till försäljning så att jag kan sälja det.

**Comment by Vurpas** [comment]
db.gameAds.insertOne({created_at: Date(), updated_at: Date(), title: "Wingspan", description: "I spelet tar du rollen som en fågelentusiast - en forskare, ornitolog, samlare eller fågelskådare som försöker attrahera de bästa fåglarna till ditt egna reservat. Varje fågel bidrar med sina unika förmågor för att skapa en kedjereaktion av förmågor som om de kombineras rätt kan ge fantastiska resultat. De tre huvudhandlingarna som kan hända och som kan förstärkas är: Få mer mat, Lägga ägg, Dra nya fågelkort från de dryga hundratalet unika fågelkort.", price: 360, game_details: [{creator: "Stonemaier Games"}, {time: "40-70 minutes"}, {recommended_age: "10+"}, {players: "1-5"}, {genre: "Strategy"}], photo_url: "https://images.app.goo.gl/b5euYXbQrwbTeJBC7", seller: '658d325b1c0de9655de662c6'});
