### ISSUE TITLE
Configure Login/signup methods

### ISSUE THREAD

**Issue by Vurpas** [Jerkinator/secondRoll#69]
- Create loginRequest and configure login method in auth-controller.
- Refactor Sign up method to make name, lastname, phone number and adress details mandatory.
- Create code (if-statement) to make sure email is unique when signing up in the authController.
- Refactor the adress_details-array in user model to be three separate strings with street, zip and city.
- Test in postman

**Comment by Pickadolly** [comment]
det här känns inte som ett issue som två personer ska göra? sen säger inte titeln något utan den är mest förvirrande? är login klarr eller inte? vad är det här och exakt vad innebär det? Om det handlar om annoteringar och fält så kan en person göra det

**Comment by Vurpas** [comment]
Åter igen mitt fel. Det här issuet var aldrig menat för 2 personer, det var ett större issue som jag och mia bröt ner till 2 issues så att vi skulle kunna jobba på varsitt håll utan "code with me". Jag hade lite för bråttom, formulerade issuen halvbra och glömde ändra assignees.
