### ISSUE TITLE
Configure endpoints/restrictions in webSecurityConfig

### ISSUE THREAD

**Issue by Vurpas** [Jerkinator/secondRoll#77]
- Configure the endpoints for the program in webSecurityConfig to make sure it's accessible for everyone during testing.
- Figure out what needs to be accessible to users, and what should be restricted to users. Make restrictions in webSecurityConfig for when the app is "live".
- Test in postman, all of the collections ( users, gameads, orders, auth )

Authorization for roles "admin" and "user" added, giving access to restricted endpoints.
Endpoints "api/auth/signup" and "api/auth/login" continues to have public access.

**Comment by Pickadolly** [comment]
Vad innebär det här?
Configure the endpoints for the program

och det här?
Test in postman, all of the collections ( users, gameads, orders, auth )

ett issue kan ju inte vara klart om det inte är testat? den som kollar PR ska även testa, funkar det inte så ska inte PR gå igenom.

**Comment by Vurpas** [comment]
Lite slarvigt skrivet av mig ser jag nu, det gäller inte för hela programmet utan bara i vår webSecurityConfig för att ha koll på vilka endpoints som är tillåtna för olika typer av roller. Så hela issuen hänvisar egentligen till att undersöka och programmera enpointsen i den klassen, och sen testa så att allt fungerar. Jag ska omformulera den lite!
